config/routes.rb
Rails.application.routes.draw do
  get 'lists/index'

  get 'lists/show'

  #Root Routes
  root 'boards#index'

  #Devise Routes
  devise_for :users

  #Resource Routes
  resources :boards do
    resources :lists 
  end

  #custom GET routes
  #custom POST routes
  #custom PUT routes
  #custom DELETE routes
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/board.rb
class Board < ApplicationRecord
  #Validations
  validates_presence_of :name

  # Associations
  belongs_to :user
  has_many :lists
  # Callbacks

  # Instance Methods

  # Class Methods

end

app/models/list.rb
class List < ApplicationRecord
  validates_presence_of :title

  belongs_to :board 
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :boards
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  before_action :authenticate_user!     # changes depending on what ever you name devise model 
end

app/controllers/boards_controller.rb
class BoardsController < ApplicationController
  before_action :set_board, only: [:show, :edit, :update, :destroy]

  # GET /boards
  # GET /boards.json
  def index
    @boards = current_user.boards
  end

  # GET /boards/1
  # GET /boards/1.json
  def show
  end

  # GET /boards/new
  def new
    @board = Board.new
  end

  # GET /boards/1/edit
  def edit
  end

  # POST /boards
  # POST /boards.json
  def create
    @board = current_user.boards.new(board_params)

    respond_to do |format|
      if @board.save
        format.html { redirect_to @board, notice: 'Board was successfully created.' }
        format.json { render :show, status: :created, location: @board }
      else
        format.html { render :new }
        format.json { render json: @board.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /boards/1
  # PATCH/PUT /boards/1.json
  def update
    respond_to do |format|
      if @board.update(board_params)
        format.html { redirect_to @board, notice: 'Board was successfully updated.' }
        format.json { render :show, status: :ok, location: @board }
      else
        format.html { render :edit }
        format.json { render json: @board.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /boards/1
  # DELETE /boards/1.json
  def destroy
    @board.destroy
    respond_to do |format|
      format.html { redirect_to boards_url, notice: 'Board was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_board
      @board = current_user.boards.find(params[:id])   # this needs .boards because im an idiot 
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def board_params
      params.require(:board).permit(:name)
    end
end

app/controllers/lists_controller.rb
class ListsController < ApplicationController
  before_action :set_board
  before_action :set_list, only: [:show, :update, :destroy]

  def index
    @lists = @boards.lists
  end

  def show
  end

  def create
    @list = @board.lists.new(list_params)
    if @list.save
      render :list
    else
      render json: { errors: @list.errors.full_messages }, status: 401
    end
  end

  def update
    if @list.update(list_params)
      render :list
    else
      render json: { errors: @list.errors.full_messages }, status: 401
    end
  end

  def destroy
    @list.destroy
    head :ok
  end

  private
    def list_params
      params.require(:list).permit(:title)
    end

    def set_board
      @board = current_user.boards.find(params[:board_id])
    end

    def set_list
      @lists = @baord.lists.find(params[:id])
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/boards_helper.rb
module BoardsHelper
end

app/helpers/lists_helper.rb
module ListsHelper
end

app/views/boards/_form.html.haml
= form_for @board do |f|
  - if @board.errors.any?
    #error_explanation
      %h2= "#{pluralize(@board.errors.count, "error")} prohibited this board from being saved:"
      %ul
        - @board.errors.full_messages.each do |msg|
          %li= msg

  .field
    = f.label :name
    = f.text_field :name
  .actions
    = f.submit 'Save'

app/views/boards/edit.html.haml
%h1 Editing board

= render 'form'

= link_to 'Show', @board
\|
= link_to 'Back', boards_path

app/views/boards/index.html.haml
-react_component('Boards', boards: @boards)

= react_component('AjaxBoards')

app/views/boards/new.html.haml
%h1 New board

= render 'form'

= link_to 'Back', boards_path

app/views/boards/show.html.haml
%p#notice= notice

%p
  %b Name:
  = @board.name

= link_to 'Edit', edit_board_path(@board)
\|
= link_to 'Back', boards_path

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>TrelloClone</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all' %>
    <%= javascript_include_tag 'application' %>
  </head>

  <body>
      <!-- <div class='container'> -->
    <%= yield %>
      <!-- </div> -->
  </body>
</html>